### ISSUE TITLE
No Render

### ISSUE THREAD

**Issue by WarriorCrystal** [Mapeadoh/AnasheClientPlus#2]
si qres te puedo dar el src de la ultima version de cb+ la cual no voy a continuar donde esta bien hecho el no render de "leuxbackdoor" en pocas palabras me lo pastearon, leuxbackdoor es cb+ con rat literalmente

**Comment by Mapeadoh** [comment]
yo por mi si, como vos quieras

**Comment by WarriorCrystal** [comment]
te lo pase por dm

**Comment by WarriorCrystal** [comment]
checa dm ctm
